language: python
python:
  - "2.7"
  - "3.6"
os: linux
dist: bionic
cache: pip
addons:
  apt:
    update: true
    packages:
      - openjdk-8-jdk
env:
  - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - pip install -e .
script:
  - bash python/run-tests.sh
  - pip install scikit-learn==0.20.4 && bash python/run-tests.sh
