language: python
python:
  - "3.6"
os: linux
dist: bionic
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
script:
  - python python/test/basic_travis_spark_test.py
  - bash python/run-tests-with-doctests.sh
