language: python
python:
  - "3.6"
os: linux
dist: bionic
cache: pip
addons:
  apt:
    update: true
    packages:
      - openjdk-8-jdk
env:
  - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - pip install -e .
script:
  - python python/test/basic_travis_spark_test.py
  - bash python/run-tests-with-doctests.sh
